### ISSUE TITLE
[Bug]  Deploy to Firebase Hosting on merge github action 빌드 오류

### ISSUE THREAD

**Issue by nakyeonko3** [Dev-FE-1/Toy_Project_II_team4#8]
### 🐞 설명

빌드 오류 발생함.
![image](https://github.com/user-attachments/assets/97e8363c-6474-4856-a343-c2af4bf50d83)

예상 원인
아마 npm package-lock.json 파일이 제대로 작성이 안되어 있을 가능성이 높음.

### 💻 버그 시뮬레이션

이 명령어 실행시 오류가 발행함.
```
npm ci 
```

```
Run npm ci && npm run build
npm error code EUSAGE
npm error
npm error `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm error
npm error Missing: @emotion/react@11.13.0 from lock file
npm error Missing: @emotion/styled@11.13.0 from lock file
npm error Missing: sass@1.77.8 from lock file
npm error Missing: @emotion/babel-plugin@11.12.0 from lock file
npm error Missing: @emotion/cache@11.13.1 from lock file
npm error Missing: @emotion/serialize@1.3.0 from lock file
npm error Missing: @emotion/use-insertion-effect-with-fallbacks@1.1.0 from lock file
npm error Missing: @emotion/utils@1.4.0 from lock file
npm error Missing: @emotion/weak-memoize@0.4.0 from lock file
npm error Missing: @emotion/hash@0.9.2 from lock file
npm error Missing: @emotion/memoize@0.9.0 from lock file
npm error Missing: convert-source-map@1.9.0 from lock file
npm error Missing: escape-string-regexp@4.0.0 from lock file
npm error Missing: @emotion/sheet@1.4.0 from lock file
npm error Missing: @emotion/unitless@0.9.0 from lock file
npm error Missing: @emotion/is-prop-valid@1.3.0 from lock file
npm error Missing: @popperjs/core@2.11.8 from lock file
npm error Missing: chokidar@3.6.0 from lock file
npm error Missing: immutable@4.3.7 from lock file
npm error Missing: anymatch@3.1.3 from lock file
npm error Missing: fsevents@2.3.3 from lock file
npm error Missing: glob-parent@5.1.2 from lock file
npm error Missing: is-binary-path@2.1.0 from lock file
npm error Missing: normalize-path@3.0.0 from lock file
npm error Missing: readdirp@3.6.0 from lock file
npm error Missing: binary-extensions@2.3.0 from lock file
npm error
npm error Clean install a project
npm error
npm error Usage:
npm error npm ci
npm error
npm error Options:

```

**Comment by nakyeonko3** [comment]
## 해결완료

깃허브 액션 워크 플로우를 bun으로 install하는 방향으로 바꿔버림.

## 원인

### package-lock.json에 linux 에 필요한 종속성이 명시가 안되는 문제 
 - package-lock.json의 플랫폼 의존성 문제가 발생함.
- package-lock.json에 ubuntu linux 환경에 필수로 들어가야할 의존성들이 포함되지 않는 문제를 해결함.
- bun install 할 때는 그런 문제가 없음
- **더 공부가 필요함. package-lock.json가 왜 다른 플랫폼 의존성이 포함이 되지 않는 이유를 알아야 될것 같다.** https://docs.npmjs.com/cli/v10/configuring-npm/package-lock-json
- bun으로 어떻게 의존성이 설치 되는지 정확히 모르겠다. 이부분도 공부가 필요함. https://bun.sh/guides/runtime/cicd



```
# This file was auto-generated by the Firebase CLI
# https://github.com/firebase/firebase-tools
name: Deploy to Firebase Hosting on PR
on: pull_request
permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository && contains(github.event.pull_request.labels.*.name, 'preview') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - run: bun install
      - run: bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TOY_PROJECT2_TEAM4_FASTCOM4 }}
          channelId: live
          projectId: toy-project2-team4-fastcom4
          
```
